steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/project-one-315608/project-one-gcp:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project-one-315608/project-one-gcp:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'project-one-315608', '--region=asia-south1', '--platform=managed', '--image=gcr.io/project-one-315608/project-one-gcp:$SHORT_SHA']
- name: "gcr.io/PROJECT_ID/sonar-scanner:latest"
  args: 
    - "-Dsonar.host.url=https://sonarcloud.io/"
    - "-Dsonar.login=eff2c78ae9fa629347b491ec50873f896615cd0f"
    - "-Dsonar.projectKey=sample-project"
    - "-Dsonar.sources=."
 - name: "gcr.io/cloud-builders/docker"
   args: 
     - "build"
     - "-t"
     - "gcr.io/PROJECT_ID/html-css-website"
     - "."
images: 
  - "gcr.io/PROJECT_ID/html-css-website"
