steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_URL}:${_IMAGE_TAG}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_IMAGE_URL}:${_IMAGE_TAG}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'project-one-315608', '--region=asia-south1', '--platform=managed', '--image=gcr.io/project-one-315608/project-one-gcp:${_IMAGE_TAG}']
substitutions:
  _IMAGE_URL: 'gcr.io/project-one-315608/project-one-gcp'
  _IMAGE_TAG: 'latest'
timeout: 900s
