steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/project-one-31560/project-one-gcp:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project-one-315608/project-one-gcp:$SHORT_SHA'', '.']
##33
