name: Snyk on GIT
on: push
jobs:
  Snyksecurity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - name: Snyk test
      run: snyk test --all-projects --json-file-output=snyk.json
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: Snyk test
      run: snyk test --all-projects --json-file-output=snyk.json
      continue-on-error: true
